---
title: "Assignment 2"
output: pdf_document
date: "2023-08-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

# Question 1

```{r histogramRolls}

roll <- function(max_rolls, sides, num_of_dice, biasVector){
  allRolls = c()
  for(x in 1:max_rolls){
    die <- 1:8
    dice <- sample(die, size =num_of_dice , prob = biasVector)
    allRolls <- append(allRolls,sum(dice))
  }
  hist(allRolls,xlab="Sum of 3 rolls", ylab="Number of rolls")
}

roll(50000, 8, 3, c(1,1,1,1,1,1,3,1)/10)

```

# Question 2

```{r rescaleFunction, error=TRUE}
rescale01 <- function(x){
  rangeOfVector <- range(x, na.rm =TRUE, finite = TRUE)
  x[x == -Inf] = rangeOfVector[1]
  x[x == Inf] = rangeOfVector[2]
  for(i in 1:length(x)){
    if(!is.numeric(x[i])){
      stop("inputs must all be numeric")
    }
    x[i] <- (x[i] - rangeOfVector[1])/(rangeOfVector[2] - rangeOfVector[1])
  }
  return(x)
}
rescale01(c(Inf, 1, 2,3, -Inf))
#to show the error message
rescale01(c('a',2,4,1,Inf))
```

# Question 3

```{r checkForNA, error=TRUE}
commonNA <- function(x,y){
  if(length(x) != length(y)){
    stop("vectors must be the same length")
  }
  numberOfCommonNA <- 0
  for(i in 1:length(x)){
    if((is.na(x[i])) && (is.na(y[i]))){
      numberOfCommonNA <- numberOfCommonNA + 1
    }
  }
  return(numberOfCommonNA)
}
commonNA(c(NA,1,2,3,NA,5), c(NA,2,NA,4,NA,5))
#To show the error message
commonNA(c(1,2,3,4),c(1,2,3))
```

# Question 4

```{r fizzbuzz}
fizzbuzz <- function(x){
  if(x%%5==0 && x%%3==0){
    return("fizzbuzz")
  }
  else if(x%%5 == 0){
    return("buzz")
  }
  else if(x%%3 == 0){
    return("fizz")
  }
  return(x) 
}
fizzbuzz(3)
fizzbuzz(5)
fizzbuzz(15)
fizzbuzz(1)
```

# Question 5

```{r cutFunction}
get_temp_desc <- function(temp){
  cut(temp, breaks = c(-Inf,0,10,20,30,Inf), labels= c("freezing","cold","cool","warm","hot"))
  
}
get_temp_desc(-1)
get_temp_desc(10)
get_temp_desc(12)
get_temp_desc(23)
get_temp_desc(33)
```

