---
title: "assignment3"
output: pdf_document
date: "2023-08-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r requiredPackages}
require(ggplot2)
```

## Question 1

```{r pointAndLine}

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy), se = FALSE)
```

## Question 2

```{r pointAndLine2}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color=drv)) +
  geom_smooth(mapping = aes(x = displ, y = hwy), se = FALSE, color='blue')
```

## Question 3

```{r pointAndLine3}
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv), se = FALSE, color = 'blue')+
  geom_point(mapping = aes(x = displ, y = hwy, color=drv))
```

## Question 4

```{r pointAndLine4}
ggplot(data = mpg) + 
  geom_jitter(mapping = aes(x = cty, y = hwy, color=class))
```

## Question 5

```{r pointAndLine5}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = hwy, y = cyl), shape = 17,color='orange')+
  facet_wrap(~class, nrow = 3)
```
